baseURL: 'https://vnquant.vn/'
title: The Financial Engineer
theme: [PaperMod]
defaultContentLanguage: vi
googleAnalytics: "G-BEV31LZP2J"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disableKinds: ['section']

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10

params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  label:
    text: 'The Financial Engineer'
  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
  # home-info mode
  homeInfoParams:
      Title: 'The Financial Engineer'
      Content: 'Analyzing Vietnam financial market quantitatively'

  socialIcons:
    - name: facebook
    - name: github
      url: 'https://github.com/hungha11'
    - name: stackoverflow
  analytics:
      google:
        SiteVerificationTag: 'G-BEV31LZP2J'
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

markup:
  highlight:
    lineNos: true
    style: monokai
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
params:
  math: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: Search
      url: search/
      weight: 8
    - name: Tags
      url: tags/
      weight: 7
    - name: Archive
      url: archives/
      weight: 6
    - name: About
      url: about/
      weight: 5

giscus:
    repo: "$user/$repo"
    repoID: "$someID"
    category: "General"
    categoryID: "$categoryID"
    mapping: "url"
    inputPosition: "top"