baseURL: 'https://vnquant.vn/'
title: 'The Financial Engineer'
theme: [PaperMod]
defaultContentLanguage: vi

# Google Analytics (GA4)
googleAnalytics: 'G-QN9CH6KS4T'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disableKinds: ['section']

sitemap:
  changefreq: 'monthly'
  filename: 'sitemap.xml'
  priority: 0.5

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10

params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  label:
    text: 'The Financial Engineer'

  profileMode:
    enabled: false

  homeInfoParams:
    Title: 'The Financial Engineer'
    Content: 'Analyzing Vietnam financial market quantitatively'

  socialIcons:
    - name: facebook
    - name: github
      url: 'https://github.com/hungha11'
    - name: stackoverflow

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title','permalink','summary','content']

  math: true

  # If you want Giscus comments, nest them here:
  giscus:
    repo: "$user/$repo"
    repoID: "$someID"
    category: "General"
    categoryID: "$categoryID"
    mapping: "url"
    inputPosition: "top"

markup:
  highlight:
    lineNos: true
    style: monokai
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - ['\\[','\\]']
            - ['$$','$$']
          inline:
            - ['\\(','\\)']
        enable: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Search
      url: search/
      weight: 8
    - name: Tags
      url: tags/
      weight: 7
    - name: Archive
      url: archives/
      weight: 6
    - name: About
      url: about/
      weight: 5
