baseURL: 'https://vnquant.vn/'
title: 'The Financial Engineer'
theme: [PaperMod]
defaultContentLanguage: vi

# Google Analytics (GA4)
googleAnalytics: 'G-BEV31LZP2J'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disableKinds: ['section']

sitemap:
  changefreq: 'monthly'
  filename: 'sitemap.xml'
  priority: 0.5

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10

params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false

  # Display settings
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  disableSpecial1stPost: false
  disableScrollToTop: false

  # Table of Contents
  UseHugoToc: true
  showtoc: true
  tocopen: true

  comments: true
  hidemeta: false
  hideSummary: false

  # Branding
  label:
    text: 'The Financial Engineer'
  profileMode:
    enabled: false

  # Cover images
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # Search (Fuse.js)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

  # Math rendering
  math: true
  # engine: katex

  # Giscus comment widget
  giscus:
    repo: "$user/$repo"
    repoID: "$someID"
    category: "General"
    categoryID: "$categoryID"
    mapping: "url"
    inputPosition: "top"

markup:
  highlight:
    lineNos: true
    style: monokai

  goldmark:
    parser:
      attribute:
        enable: true
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Search
      url: search/
      weight: 8
    - name: Tags
      url: tags/
      weight: 7
    - name: Archive
      url: archives/
      weight: 6
    - name: About
      url: about/
      weight: 5
